make flash script only compile & flash

diff --git a/.local/bin/flash-keyboard b/.local/bin/flash-keyboard
--- a/.local/bin/flash-keyboard
+++ b/.local/bin/flash-keyboard
@@ -2,39 +2,15 @@
 
 main () {
     KEYMAP="redxtech"
-    QMK_HOME="$HOME/Code/qmk_firmware"
-    KBD_PROFILE="gmmk/pro/ansi"
-    KEYMAP_DIR="$QMK_HOME/keyboards/$KBD_PROFILE/keymaps/$KEYMAP"
+    KEYBD="gmmk/pro/ansi"
 
-    if test -f "$HOME/Downloads/$KEYMAP.json"; then
-        echo "Keymap found in downloads! Using that..."
+    echo "Compiling firmware..."
+    qmk compile || (echo "Compiling firmware failed, exiting..." && return 1)
 
-        echo "Moving $KEYMAP.json from downloads..."
-        cp "$HOME/Downloads/$KEYMAP.json" "$HOME/Downloads/$KEYMAP-installed.json" || return 1
-        mv "$HOME/Downloads/$KEYMAP.json" "$KEYMAP_DIR/$KEYMAP.json" || return 1
-    fi
+    echo "Flashing board..."
+    qmk flash -km "$KEYMAP" -kb "$KEYBD" || (echo "Flashing firmware failed, exiting..." && return 1)
 
-    echo "Compiling $KEYMAP.json to keymap.c..."
-    qmk json2c -o "$KEYMAP_DIR/keymap.c" "$KEYMAP_DIR/$KEYMAP.json" || return 1
-
-    echo "Taking overship of keymap.c..."
-    sudo chown gabe "$KEYMAP_DIR/keymap.c"
-
-    echo "Appending C code to $KEYMAP/keymap.c..."
-    cat "$KEYMAP_DIR/macros.c" | sudo tee -a "$KEYMAP_DIR/keymap.c" >/dev/null
-    cat "$KEYMAP_DIR/rotary.c" | sudo tee -a "$KEYMAP_DIR/keymap.c" >/dev/null
-
-    echo "Keymap ready to flash!"
-
-    if test "$1" = "flash"; then
-        echo "Compiling firmware..."
-        qmk compile || (echo "Compiling firmware failed, exiting..." && return 1)
-
-        echo "Flashing board..."
-        qmk flash -km "$KEYMAP" || (echo "Flashing firmware failed, exiting..." && return 1)
-
-        echo "Flashing complete!"
-    fi
+    echo "Flashing complete!"
 }
 
 main "$1"
