start install scripts for arch

diff --git a/.local/bin/scripts/install/install b/.local/bin/scripts/install/install
--- a/.local/bin/scripts/install/install
+++ b/.local/bin/scripts/install/install
@@ -1,9 +1,14 @@
 #!/usr/bin/env sh
 
+# TODO: implement better error handling from called scripts
+
 # main function to call the proper installation functions
 main () {
     # set default values
     CURRENT_DISTRO="arch" # TODO: this will be set dynamically in the future
+
+    # set install script directory
+    export INSTALL_SCRIPT_DIR="$HOME/.local/bin/scripts/install"
     
     # set variable for line separators (25 of -)
     DASH_LINE="-------------------------"
@@ -14,7 +19,8 @@ main () {
             echo "You are running arch linux!"
             echo "Loading arch installation..."
             echo "$DASH_LINE"
-            . "./arch/install.sh"
+            # shellcheck source=./arch/install.sh
+            . "$INSTALL_SCRIPT_DIR/arch/install.sh" || echo "Arch installation failed!"
             echo "$DASH_LINE"
             echo "Arch installation completed!"
             echo "$DASH_LINE"
